# Generated by Django 4.2.15 on 2025-01-18 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Desc', models.TextField()),
                ('Type', models.CharField(default='None', max_length=50)),
                ('BodyPart', models.CharField(max_length=50)),
                ('Equipment', models.CharField(default='None', max_length=50)),
                ('Level', models.CharField(default='None', max_length=50)),
                ('Repetitions', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'List of Workouts',
                'verbose_name_plural': 'Workouts',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(blank=True, max_length=255, null=True)),
                ('session_date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workouts', models.ManyToManyField(to='machine_learning.workout')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('repetitions', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('session_number', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_learning.workout')),
            ],
            options={
                'verbose_name': 'List of User Progress',
                'verbose_name_plural': 'User Progress',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sex', models.CharField(max_length=10)),
                ('Age', models.PositiveIntegerField()),
                ('Height', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Hypertension', models.CharField(default='No', max_length=10)),
                ('Diabetes', models.CharField(default='No', max_length=10)),
                ('BMI', models.FloatField()),
                ('Level', models.CharField(default='Normal', max_length=50)),
                ('Fitness_Goal', models.CharField(default='Weight_Loss', max_length=50)),
                ('Fitness_Type', models.CharField(default='Cardio_Fitness', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List of User Profiles',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
