# Generated by Django 4.2.15 on 2025-01-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='session_name',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='workouts',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='incomplete_workouts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='total_reps_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='session_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
