# Generated by Django 4.2.15 on 2025-01-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0002_remove_userprofile_diabetes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Diabetes',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Hypertension',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
