# Generated by Django 4.2.15 on 2025-01-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0002_remove_workoutsession_is_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutsession',
            old_name='is_complete',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='incomplete_workouts',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='total_reps_completed',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='session_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='workouts',
            field=models.ManyToManyField(to='machine_learning.workout'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='session_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
