# Generated by Django 4.2.15 on 2025-01-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0003_rename_is_complete_workoutsession_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='incomplete_workouts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='total_reps_completed',
            field=models.IntegerField(default=0),
        ),
    ]
