# Generated by Django 4.2.15 on 2025-01-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0004_workoutsession_completion_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='session_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
