# Generated by Django 4.2.15 on 2025-01-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0005_workoutsession_session_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='session_number',
            field=models.IntegerField(default=1),
        ),
    ]
