# Generated by Django 4.2.15 on 2025-01-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0006_alter_userprogress_session_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutsession',
            old_name='total_reps_completed',
            new_name='total_repetitions_completed',
        ),
    ]
