# Generated by Django 4.2.15 on 2025-01-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0007_rename_total_reps_completed_workoutsession_total_repetitions_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='day_1_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='day_2_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='day_3_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='day_4_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='day_5_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='day_6_progress',
            field=models.IntegerField(default=0),
        ),
    ]
