# Generated by Django 4.2.15 on 2025-01-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0008_userprogress_day_1_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='day_1_progress',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='day_2_progress',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='day_3_progress',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='day_4_progress',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='day_5_progress',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='day_6_progress',
        ),
    ]
