# Generated by Django 4.2.15 on 2025-02-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0010_userprogress_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_reps',
            field=models.IntegerField(default=100),
        ),
    ]
