# Generated by Django 4.2.15 on 2025-02-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0013_alter_userprofile_preferred_reps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_reps',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='preferred_reps',
            field=models.IntegerField(default=10),
        ),
    ]
