# Generated by Django 4.2.15 on 2025-02-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0014_remove_userprofile_preferred_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='preferred_reps',
            field=models.IntegerField(default=0),
        ),
    ]
