# Generated by Django 4.2.15 on 2025-02-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0015_alter_userprogress_preferred_reps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='preferred_reps',
            field=models.IntegerField(default=100),
        ),
    ]
