# Generated by Django 4.2.15 on 2025-02-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0017_alter_userprogress_preferred_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='routine_number',
            field=models.IntegerField(default=1),
        ),
    ]
